# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'moip-app' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for moip-app
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'SVProgressHUD'
  pod 'JDStatusBarNotification'

  target 'moip-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'moip-appUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
